name: Unit Tests

on: push

jobs:
  integration:
    runs-on: ubuntu-20.04
    container: python:3.11.3-slim

    steps:
      - name: Install container dependencies
        run: |
          apt update
          apt install -y make software-properties-common gnupg2
          add-apt-repository -y ppa:git-core/ppa
          apt install -y git make
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install poetry
          make init
          pip3 install -U pip setuptools
          pip3 install poetry coverage-badge

      - name: Run Tests
        run: |
          make test
